# coding: utf-8
from enum import Enum


class Ticker(Enum):
    AMAZON: str = 'AMZN'
    AMERICAN_EXPRESS: str = 'AXP'
    AMGEN: str = 'AMGN'
    APPLE: str = 'AAPL'
    BOEING: str = 'BA'
    CATERPILLAR: str = 'CAT'
    CHEVRON: str = 'CVX'
    CISCO: str = 'CSCO'
    COCACOLA: str = 'KO'
    DISNEY: str = 'DIS'
    DOW_INC: str = 'DOW'
    DOW_JONES: str = 'DJI'
    FACEBOOK: str = 'FB'
    GOLDMAN_SACHS: str = 'GS'
    GOOGLE: str = 'GOOG'
    HOME_DEPOT: str = 'HD'
    HONEYWELL: str = 'HON'
    INTEL: str = 'INTC'
    IBM: str = 'IBM'
    JOHNSON_JOHNSON: str = 'JNJ'
    JPMORGAN: str = 'JPM'
    MCDONALDS: str = 'MCD'
    MERCK: str = 'MRK'
    MICROSOFT: str = 'MSFT'
    NETES: str = 'NTES'
    NIKE: str = 'NKE'
    PROCTER_GAMBLE: str = 'PG'
    SALESFORCE: str = 'CRM'
    TESLA: str = 'TSLA'
    THREE_M: str = 'MMM'
    TRAVELERS: str = 'TRV'
    UNITED_HEALTH: str = 'UNH'
    VERIZON: str = 'VZ'
    VISA: str = 'V'
    WALGREENS: str = 'WBA'
    WALMART: str = 'WMT'
